blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    url: https://github.com/graysoncadams/scrolly/security/advisories/new
    about: Report a security vulnerability privately
